version: 1.0.{build}

image: Visual Studio 2017


init:
- ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200 api.nuget.org")' 

hosts:
  api.nuget.org: 93.184.221.200 

before_build:
- nuget restore

build:
  verbosity: minimal
